name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]  # Ganti 'main' kalau branch lu beda

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AKSARA_9505C }}
          channelId: live
          projectId: aksara-9505c
